package com.nominalista.expenses.model

import androidx.room.TypeConverter

enum class Currency(val code: String,
                    val title: String,
                    val symbol: String,
                    val flag: String) {

    AED("AED", "Emirati Dirham", "د.إ", "\uD83C\uDDE6\uD83C\uDDEA"),
    AFN("AFN", "Afghanistan Afghani", "؋", "\uD83C\uDDE6\uD83C\uDDEB"),
    ARS("ARS", "Argentina Peso", "$", "\uD83C\uDDE6\uD83C\uDDF7"),
    AUD("AUD", "Australian Dollar", "$", "\uD83C\uDDE6\uD83C\uDDFA"),
    BBD("BBD", "Barbados Dollar", "$", "\uD83C\uDDE7\uD83C\uDDE7"),
    BDT("BDT", "Bangladeshi Taka", "Tk", "\uD83C\uDDE7\uD83C\uDDE9"),
    BGN("BGN", "Bulgarian Lev", "лв", "\uD83C\uDDE7\uD83C\uDDEC"),
    BHD("BHD", "Bahraini Dinar", "BD", "\uD83C\uDDE7\uD83C\uDDED"),
    BMD("BMD", "Bermuda Dollar","$", "\uD83C\uDDE7\uD83C\uDDF2"),
    BND("BND", "Brunei Darussalam Dollar","$", "\uD83C\uDDE7\uD83C\uDDF3"),
    BOB("BOB", "Bolivia Bolíviano","\$b", "\uD83C\uDDE7\uD83C\uDDF4"),
    BRL("BRL", "Brazil Real","R$", "\uD83C\uDDE7\uD83C\uDDF7"),
    BTN("BTN", "Bhutanese Ngultrum","Nu.", "\uD83C\uDDE7\uD83C\uDDF9"),
    BZD("BZD", "Belize Dollar","BZ$", "\uD83C\uDDE7\uD83C\uDDFF"),
    CAD("CAD", "Canada Dollar","$", "\uD83C\uDDE8\uD83C\uDDE6"),
    CHF("CHF", "Switzerland Franc","CHF", "\uD83C\uDDE8\uD83C\uDDED"),
    CLP("CLP", "Chile Peso","$", "\uD83C\uDDE8\uD83C\uDDF1"),
    CNY("CNY", "China Yuan Renminbi","¥", "\uD83C\uDDE8\uD83C\uDDF3"),
    COP("COP", "Colombia Peso","$", "\uD83C\uDDE8\uD83C\uDDF4"),
    CRC("CRC", "Costa Rica Colon","₡", "\uD83C\uDDE8\uD83C\uDDF7"),
    CZK("CZK", "Czech Korona", "Kč", "\uD83C\uDDE8\uD83C\uDDFF"),
    DKK("DKK", "Denmark Krone","kr", "\uD83C\uDDE9\uD83C\uDDF0"),
    DOP("DOP", "Dominican Republic Peso","RD$", "\uD83C\uDDE9\uD83C\uDDF4"),
    EGP("EGP", "Egypt Pound","£", "\uD83C\uDDEA\uD83C\uDDEC"),
    ETB("ETB", "Ethiopian Birr","Br", "\uD83C\uDDEA\uD83C\uDDF9"),
    EUR("EUR", "Euro", "€", "\uD83C\uDDEA\uD83C\uDDFA"),
    GBP("GBP", "British Pound", "£", "\uD83C\uDDEC\uD83C\uDDE7"),

//    GEL("GEL", "Georgian Lari","₾", R.drawable.flag_gel),
//    GHS("GHS", "Ghana Cedi","¢", R.drawable.flag_ghs),
//    GMD("GMD", "Gambian dalasi","D", R.drawable.flag_gmd),
//    GYD("GYD", "Guyana Dollar","$", R.drawable.flag_gyd),
//    HKD("HKD", "Hong Kong Dollar","$", R.drawable.flag_hkd),
//    HRK("HRK", "Croatia Kuna","kn", R.drawable.flag_hrk),
//    HUF("HUF", "Hungary Forint","Ft", R.drawable.flag_huf),
//    IDR("IDR", "Indonesia Rupiah","Rp", R.drawable.flag_idr),
//    ILS("ILS", "Israel Shekel","₪", R.drawable.flag_ils),
//    INR("INR", "India Rupee","0", R.drawable.flag_inr),
//    ISK("ISK", "Iceland Krona","kr", R.drawable.flag_isk),
//    JMD("JMD", "Jamaica Dollar","J$", R.drawable.flag_jmd),
//    JPY("JPY", "Japanese Yen","¥", R.drawable.flag_jpy),
//    KES("KES", "Kenyan Shilling","KSh", R.drawable.flag_kes),
//    KRW("KRW", "Korea (South) Won","₩", R.drawable.flag_krw),
//    KWD("KWD", "Kuwaiti Dinar","د.ك", R.drawable.flag_kwd),
//    KYD("KYD", "Cayman Islands Dollar","$", R.drawable.flag_kyd),
//    KZT("KZT", "Kazakhstan Tenge","лв", R.drawable.flag_kzt),
//    LAK("LAK", "Laos Kip","₭", R.drawable.flag_lak),
//    LKR("LKR", "Sri Lanka Rupee","₨", R.drawable.flag_lkr),
//    LRD("LRD", "Liberia Dollar","$", R.drawable.flag_lrd),
//    LTL("LTL", "Lithuanian Litas","Lt", R.drawable.flag_ltl),
//    MAD("MAD", "Moroccan Dirham","MAD", R.drawable.flag_mad),
//    MDL("MDL", "Moldovan Leu","MDL", R.drawable.flag_mdl),
//    MKD("MKD", "Macedonia Denar","ден", R.drawable.flag_mkd),
//    MNT("MNT", "Mongolia Tughrik","₮", R.drawable.flag_mnt),
//    MUR("MUR", "Mauritius Rupee","₨", R.drawable.flag_mur),
//    MWK("MWK", "Malawian Kwacha","MK", R.drawable.flag_mwk),
//    MXN("MXN", "Mexico Peso","$", R.drawable.flag_mxn),
//    MYR("MYR", "Malaysia Ringgit","RM", R.drawable.flag_myr),
//    MZN("MZN", "Mozambique Metical","MT", R.drawable.flag_mzn),
//    NAD("NAD", "Namibia Dollar","$", R.drawable.flag_nad),
//    NGN("NGN", "Nigeria Naira","₦", R.drawable.flag_ngn),
//    NIO("NIO", "Nicaragua Cordoba","C$", R.drawable.flag_nio),
//    NOK("NOK", "Norway Krone","kr", R.drawable.flag_nok),
//    NPR("NPR", "Nepal Rupee","₨", R.drawable.flag_npr),
//    NZD("NZD", "New Zealand Dollar","$", R.drawable.flag_nzd),
//    OMR("OMR", "Oman Rial","﷼", R.drawable.flag_omr),
//    PEN("PEN", "Peru Sol","S/.", R.drawable.flag_pen),
//    PGK("PGK", "Papua New Guinean Kina","K", R.drawable.flag_pgk),
//    PHP("PHP", "Philippines Peso","₱", R.drawable.flag_php),
//    PKR("PKR", "Pakistan Rupee","₨", R.drawable.flag_pkr),

    PLN("PLN", "Polski zloty", "zł", "\uD83C\uDDF5\uD83C\uDDF1"),
    PYG("PYG", "Paraguay Guarani","Gs", "\uD83C\uDDF5\uD83C\uDDFE"),
    QAR("QAR", "Qatar Riyal","﷼", "\uD83C\uDDF6\uD83C\uDDE6"),
    RON("RON", "Romania Leu","lei", "\uD83C\uDDF7\uD83C\uDDF4"),
    RSD("RSD", "Serbia Dinar","Дин.", "\uD83C\uDDF7\uD83C\uDDF8"),
    RUB("RUB", "Russia Ruble","₽", "\uD83C\uDDF7\uD83C\uDDFA"),
    SAR("SAR", "Saudi Arabia Riyal","﷼", "\uD83C\uDDF8\uD83C\uDDE6"),
    SEK("SEK", "Sweden Krona","kr", "\uD83C\uDDF8\uD83C\uDDEA"),
    SGD("SGD", "Singapore Dollar","$", "\uD83C\uDDF8\uD83C\uDDEC"),
    SOS("SOS", "Somalia Shilling","S", "\uD83C\uDDF8\uD83C\uDDF4"),
    SRD("SRD", "Suriname Dollar","$", "\uD83C\uDDF8\uD83C\uDDF7"),
    THB("THB", "Thailand Baht","฿", "\uD83C\uDDF9\uD83C\uDDED"),
    TRY("TRY", "Turkish Lira", "₺", "\uD83C\uDDF9\uD83C\uDDF7"),
    TTD("TTD", "Trinidad and Tobago Dollar","TT$", "\uD83C\uDDF9\uD83C\uDDF9"),
    TWD("TWD", "Taiwan New Dollar","NT$", "\uD83C\uDDF9\uD83C\uDDFC"),
    TZS("TZS", "Tanzanian Shilling","TSh", "\uD83C\uDDF9\uD83C\uDDFF"),
    UAH("UAH", "Ukraine Hryvnia","₴", "\uD83C\uDDFA\uD83C\uDDE6"),
    UGX("UGX", "Ugandan Shilling","USh", "\uD83C\uDDFA\uD83C\uDDEC"),
    USD("USD", "United States Dollar", "$", "\uD83C\uDDFA\uD83C\uDDF8"),
    UYU("UYU", "Uruguay Peso","\$U", "\uD83C\uDDFA\uD83C\uDDFE"),
    VEF("VEF", "Venezuela Bolívar","Bs", "\uD83C\uDDFB\uD83C\uDDEA"),
    VND("VND", "Viet Nam Dong","₫", "\uD83C\uDDFB\uD83C\uDDF3"),
    YER("YER", "Yemen Rial","﷼", "\uD83C\uDDFE\uD83C\uDDEA"),
    ZAR("ZAR", "South Africa Rand","R", "🇿🇦");

    companion object {

        fun fromCode(code: String): Currency? {
            return Currency.values().firstOrNull { currency -> currency.code == code }
        }
    }

    val description get() = "$flag   $title ($code)"
}